name: Download Winget Manifests

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  fetch-manifests:
    name: Fetch Latest Manifests
    runs-on: ubuntu-latest
    outputs:
      updated-files: ${{ steps.determine-updated-files.outputs.updated_files }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --global user.email "dawnzac88@gmail.com"
          git config --global user.name "Dawn Zac"

      - name: Set up Git credentials
        run: |
          git remote set-url origin https://github-actions:$(echo ${{ secrets.GH_TOKEN }})@github.com/Dawnzac/manifest-update.git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install requests beautifulsoup4

      - name: Run Script to Fetch Winget Manifests
        run: python download_manifest7.py

      - name: Commit and Push Changes
        if: success()
        run: |
          git add manifests
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Update manifests"
          git push origin main

  update-azure-storage:
    name: Update Azure Storage
    needs: fetch-manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Determine Updated Files
        id: determine-updated-files
        run: |
          UPDATED_FILES=$(git diff --name-only HEAD~1)
          echo "updated_files=$UPDATED_FILES" >> $GITHUB_ENV

      - name: Set Up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload Updated Files to Azure Blob Storage
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        run: |
          # Get the list of updated files in the manifests folder
          UPDATED_FILES=$(git diff --name-only HEAD~1 | grep "^manifests/")
            
          if [ -z "$UPDATED_FILES" ]; then
            echo "No updated files in manifests folder."
            exit 0
          fi

          echo "Files to upload:"
          echo "$UPDATED_FILES"

          for FILE in $UPDATED_FILES; do
            echo "Uploading $FILE to Azure Storage..."
            az storage blob upload --file "$FILE" --container-name "manifests" --name "$FILE" --overwrite
          done
