name: Download Winget Manifests

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  fetch-manifests:
    name: Fetch Latest Manifests
    runs-on: ubuntu-latest
    outputs:
      updated-files: ${{ steps.determine-updated-files.outputs.updated_files }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --global user.email "dawnzac88@gmail.com"
          git config --global user.name "Dawn Zac"

      - name: Set up Git credentials
        run: |
          git remote set-url origin https://github-actions:$(echo ${{ secrets.GH_TOKEN }})@github.com/Dawnzac/manifest-update.git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install requests pyyaml beautifulsoup4

      - name: Run Script to Fetch Winget Manifests
        run: python download_manifest7.py

      - name: Determine Updated Files
        id: determine-updated-files
        run: |
          UPDATED_FILES=$(git diff --name-only HEAD~1)
          echo "updated_files=$UPDATED_FILES" >> $GITHUB_ENV

  update-azure-storage:
    name: Update Azure Storage
    needs: fetch-manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload Updated Files to Azure Storage
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        run: |
          if [ -n "${{ env.updated_files }}" ]; then
            for FILE in ${{ env.updated_files }}; do
              az storage blob upload \
                --container-name manifests \
                --file $FILE \
                --name $(basename $FILE)
            done
          else
            echo "No updated files to upload."
          fi
